### ISSUE TITLE
Axis/Node Labels

### ISSUE THREAD

**Issue by tk27182** [rgarcia-herrera/pyveplot#2]
Hello, thanks for creating this library, it's really useful!

Is it possible to label the axis and the nodes in the final SVG file?

**Comment by rgarcia-herrera** [comment]
Sorry for the late response. Sure, check out the example in the latest version.

**Comment by rgarcia-herrera** [comment]
Wait, I have moved this project to a gitlab repo.

https://gitlab.com/rgarcia-herrera/pyveplot
